name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Set the build number in MinVer.
      MINVERBUILDMETADATA: build.${{github.run_number}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: |
          dotnet build --no-restore --configuration Debug
      
      - name: Generate SBOM
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn Test -pv 1.0.0 -ps MyCompany -nsb https://sbom.mycompany.com -V Verbose

      - name: Upload a Build Artifact (SBOM)
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./_manifest
        
      - name: Upload a Build Artifact (DLL)
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ./*.dll

      - name: Run tests
        run: dotnet test --no-build --configuration Debug
